//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Baby_BEntities : DbContext
    {
        public Baby_BEntities()
            : base("name=Baby_BEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ChildrenArchive> ChildrenArchive { get; set; }
        public virtual DbSet<ChildrenFamily> ChildrenFamily { get; set; }
        public virtual DbSet<DefaultTemplates> DefaultTemplates { get; set; }
        public virtual DbSet<Keywords> Keywords { get; set; }
        public virtual DbSet<OldOrders> OldOrders { get; set; }
        public virtual DbSet<OldOrdersArchive> OldOrdersArchive { get; set; }
        public virtual DbSet<OrdersProducts> OrdersProducts { get; set; }
        public virtual DbSet<ProductImage> ProductImage { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<SubscriptionArchive> SubscriptionArchive { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<AccountArchive> AccountArchive { get; set; }
        public virtual DbSet<UsersArchive> UsersArchive { get; set; }
    }
}
