//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionArchive
    {
        public int IdFamily { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string ParetntsfirstName { get; set; }
        public string LastName { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> GetPostMail { get; set; }
    }
}
