//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUser { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public string FirstNameUser { get; set; }
        public string LastNameUser { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> GetPostMail { get; set; }
        public Nullable<short> TotalPayments { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
